<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LIN65004458" failures="3" tests="5" name="Error validations" time="51.559" errors="0" timestamp="2025-02-06T17:39:01 IST">
  <testcase classname="frameworks.ErrorValidationTest" name="dummyErrorTest" time="0.45">
    <skipped/>
  </testcase> <!-- dummyErrorTest -->
  <testcase classname="frameworks.ErrorValidationTest" name="dummyErrorTest" time="0.344">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at frameworks.ErrorValidationTest.dummyErrorTest(ErrorValidationTest.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- dummyErrorTest -->
  <testcase classname="frameworks.ErrorValidationTest" name="errorMessageTest" time="1.094">
    <skipped/>
  </testcase> <!-- errorMessageTest -->
  <testcase classname="frameworks.ErrorValidationTest" name="errorMessageTest" time="0.612">
    <failure type="java.lang.AssertionError" message="expected [Incorrect email or password.] but found [Incorrect email or password123.]">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password123.]
at frameworks.ErrorValidationTest.errorMessageTest(ErrorValidationTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- errorMessageTest -->
  <testcase classname="frameworks.ErrorValidationTest" name="productValidation" time="23.828">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at frameworks.ErrorValidationTest.productValidation(ErrorValidationTest.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- productValidation -->
</testsuite> <!-- Error validations -->
